CREATE TABLE category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE supplier (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(160) NOT NULL UNIQUE,
    email   VARCHAR(160),
    phone   VARCHAR(40)
);

CREATE TABLE product (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           VARCHAR(64) NOT NULL UNIQUE,
    name          VARCHAR(200) NOT NULL,
    category_id   BIGINT REFERENCES category(id),
    supplier_id   BIGINT REFERENCES supplier(id),
    unit_cost     NUMERIC(12,2) NOT NULL DEFAULT 0,
    reorder_point INTEGER NOT NULL DEFAULT 0,
    reorder_qty   INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE warehouse (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(40) NOT NULL UNIQUE,
    name   VARCHAR(160) NOT NULL,
    region VARCHAR(80)
);

CREATE TABLE inventory_level (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         BIGINT NOT NULL REFERENCES product(id),
    warehouse_id       BIGINT NOT NULL REFERENCES warehouse(id),
    quantity_on_hand   INTEGER NOT NULL DEFAULT 0,
    quantity_reserved  INTEGER NOT NULL DEFAULT 0,
    version            BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_inventory_product_warehouse UNIQUE (product_id, warehouse_id)
);

CREATE TABLE purchase_order (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES supplier(id),
    status      VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at  TIMESTAMP NOT NULL
);

CREATE TABLE purchase_order_line (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order(id),
    product_id        BIGINT NOT NULL REFERENCES product(id),
    qty               INTEGER NOT NULL,
    unit_cost         NUMERIC(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE low_stock_alert (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NOT NULL REFERENCES product(id),
    warehouse_id  BIGINT NOT NULL REFERENCES warehouse(id),
    current_qty   INTEGER NOT NULL,
    reorder_point INTEGER NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    resolved      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_product_category ON product(category_id);
CREATE INDEX idx_product_supplier ON product(supplier_id);
CREATE INDEX idx_inventory_warehouse ON inventory_level(warehouse_id);
CREATE INDEX idx_alert_resolved ON low_stock_alert(resolved);
